services:
  server:
    # build: .
    image: ghcr.io/supleed2/go-chat:latest
    container_name: go-chat
    environment:
      - "ADMIN=${ADMIN}"
      - "DB=/app/data/go-chat.db"
      - "HIST_LEN=${HIST_LEN:-10}"
      - "BIND=true"
      - "PORT=8080"
      - "NICK_MAP=/app/data/nickmap.json"
    ports:
      - "${PORT}:8080"
    volumes:
      - ${DATA}:/app/data:rw
    restart: unless-stopped
